#!/bin/bash

HOSTNAME="nfc-live"
ISO_APPLICATION="Debian Live NFC"
ISO_VOLUME="Debian live NFC $(date +%Y%m%d)"
ISO_PUBLISHER="https://code.google.com/p/nfc-live"
SUPPORT=iso-hybrid
DISTRO=wheezy
ARCH=i386
MIRROR="http://ftp.be.debian.org/debian/"

cd live || exit 1
sudo lb clean
sudo rm -rf config

# bootappend-live: see man live-boot & live-config
# group dialout: for serial boards such as OpenPCD2
lb config \
  --clean \
  --cache true \
  --binary-images $SUPPORT \
  --mode debian \
  --distribution $DISTRO \
  --architectures $ARCH \
  --mirror-bootstrap $MIRROR \
  --mirror-binary "$MIRROR" \
  --iso-application "$ISO_APPLICATION" \
  --iso-volume "$ISO_VOLUME" \
  --iso-publisher "$ISO_PUBLISHER" \
  --bootappend-live "hostname=$HOSTNAME user-default-groups=audio,cdrom,dip,floppy,video,plugdev,netdev,powerdev,scanner,bluetooth,fuse,dialout" \
  --apt-recommends false \
  --archive-areas "main contrib non-free" \
  --firmware-chroot true

sudo rsync -av ../content_for_iso/@config/ config
sudo chmod +x config/includes.chroot/usr/local/bin/*
sudo lb build
